import AppKit

/// Polls the general pasteboard and feeds new copies into the store.
final class ClipboardMonitor {
    /// Fired when a copy was skipped because it exceeded the size cap.
    var onOversized: ((_ bytes: Int, _ kindLabel: String) -> Void)?

    /// Fired for each freshly captured clip (not for clips ingested from
    /// elsewhere), so the app can push it to CloudKit without a sync feedback loop.
    var onCaptured: ((ClipItem) -> Void)?

    private let store: ClipStore
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int
    /// How many upcoming pasteboard change ticks to treat as our own writes
    /// (i.e. we re-wrote the pasteboard to synthesize ⌘V) and skip. A counter
    /// rather than a flag so multi-file sequential paste — which performs N
    /// pasteboard writes — suppresses all of its own ticks instead of just
    /// the first one.
    private var skipChangeCount = 0

    init(store: ClipStore) {
        self.store = store
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Tell the monitor to ignore the next pasteboard change — used when
    /// clipandcue itself writes to the pasteboard (e.g. delivering a picked
    /// clip) so the just-pasted item doesn't get re-added to the top.
    /// Stacks: call N times to suppress the next N changes.
    func suppressNextChange() {
        skipChangeCount += 1
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        if skipChangeCount > 0 {
            skipChangeCount -= 1
            return
        }

        switch readPasteboard() {
        case .none:
            break
        case .item(let item):
            store.add(item)
            onCaptured?(item)
        case .oversize(let bytes, let label):
            onOversized?(bytes, label)
        }
    }

    private enum ReadResult {
        case none
        case item(ClipItem)
        case oversize(bytes: Int, kindLabel: String)
    }

    /// Types password managers / apps use to mark clipboard data as not-for-history.
    private static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private func isSensitive() -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains { Self.sensitiveTypes.contains($0.rawValue) }
    }

    private func readPasteboard() -> ReadResult {
        let cap = AppSettings.shared.sizeCapBytes

        // Respect password-manager flags when the user opts in.
        if AppSettings.shared.ignoreConcealed && isSensitive() {
            return .none
        }

        // 1. Files copied from Finder (stored as path references — tiny).
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map { $0.path }
            let thumb = paths.first.flatMap { Self.fileThumbnail(forPath: $0) }
            return .item(ClipItem(kind: .files, thumbnailData: thumb, filePaths: paths))
        }

        // 2. Image data (screenshots, copied image regions).
        if let (data, utType) = bestImageData() {
            if data.count > cap {
                return .oversize(bytes: data.count, kindLabel: "image")
            }
            let image = NSImage(data: data)
            let thumb = image.flatMap { ImageUtils.thumbnailPNG(from: $0, maxDimension: 96) }
            return .item(ClipItem(
                kind: .image,
                imageData: data,
                imageUTType: utType,
                thumbnailData: thumb,
                pixelWidth: image.flatMap { ImageUtils.pixelSize($0)?.width },
                pixelHeight: image.flatMap { ImageUtils.pixelSize($0)?.height }))
        }

        // 3. Rich text (keep the RTF for fidelity, plus a plain-text preview).
        if let rtf = pasteboard.data(forType: .rtf) {
            if rtf.count > cap {
                return .oversize(bytes: rtf.count, kindLabel: "rich text")
            }
            let plain = pasteboard.string(forType: .string)
                ?? NSAttributedString(rtf: rtf, documentAttributes: nil)?.string
                ?? ""
            guard !plain.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return .none }
            return .item(ClipItem(kind: .richText, text: plain, rtfData: rtf))
        }

        // 4. Plain text.
        if let str = pasteboard.string(forType: .string) {
            guard !str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return .none }
            if str.utf8.count > cap {
                return .oversize(bytes: str.utf8.count, kindLabel: "text")
            }
            return .item(ClipItem(kind: .text, text: str))
        }

        return .none
    }

    /// For a file-kind clip, generate an inline preview when the first path
    /// points at an image NSImage knows how to load (jpg/png/heic/gif/tiff/pdf).
    /// Returns nil for everything else so the row falls back to the generic
    /// file icon. Capped by file size so we don't read a 200 MB raw onto main.
    private static func fileThumbnail(forPath path: String) -> Data? {
        let maxFileBytes = 50 * 1024 * 1024
        if let size = try? FileManager.default
            .attributesOfItem(atPath: path)[.size] as? Int,
           size > maxFileBytes {
            return nil
        }
        guard let image = NSImage(contentsOfFile: path) else { return nil }
        return ImageUtils.thumbnailPNG(from: image, maxDimension: 96)
    }

    /// Prefer PNG, fall back to TIFF.
    private func bestImageData() -> (Data, String)? {
        if let png = pasteboard.data(forType: .png) {
            return (png, "public.png")
        }
        if let tiff = pasteboard.data(forType: .tiff) {
            return (tiff, "public.tiff")
        }
        return nil
    }
}
