import AppKit

/// Polls the general pasteboard and feeds new copies into the store.
final class ClipboardMonitor {
    /// Fired when a copy was skipped because it exceeded the size cap.
    var onOversized: ((_ bytes: Int, _ kindLabel: String) -> Void)?

    /// Fired for each freshly captured clip (not for clips ingested from
    /// elsewhere), so the app can push it to CloudKit without a sync feedback loop.
    var onCaptured: ((ClipItem) -> Void)?

    private let store: ClipStore
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int
    /// How many upcoming pasteboard change ticks to treat as our own writes
    /// (i.e. we re-wrote the pasteboard to synthesize ⌘V) and skip. A counter
    /// rather than a flag so multi-file sequential paste — which performs N
    /// pasteboard writes — suppresses all of its own ticks instead of just
    /// the first one.
    private var skipChangeCount = 0

    init(store: ClipStore) {
        self.store = store
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Tell the monitor to ignore the next pasteboard change — used when
    /// clipandcue itself writes to the pasteboard (e.g. delivering a picked
    /// clip) so the just-pasted item doesn't get re-added to the top.
    /// Stacks: call N times to suppress the next N changes.
    func suppressNextChange() {
        skipChangeCount += 1
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        if skipChangeCount > 0 {
            skipChangeCount -= 1
            return
        }

        switch readPasteboard() {
        case .none:
            break
        case .item(let item):
            store.add(item)
            onCaptured?(item)
        case .oversize(let bytes, let label):
            onOversized?(bytes, label)
        }
    }

    private enum ReadResult {
        case none
        case item(ClipItem)
        case oversize(bytes: Int, kindLabel: String)
    }

    /// Types password managers / apps use to mark clipboard data as not-for-history.
    private static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private func isSensitive() -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains { Self.sensitiveTypes.contains($0.rawValue) }
    }

    private func readPasteboard() -> ReadResult {
        let cap = AppSettings.shared.sizeCapBytes

        // Respect password-manager flags when the user opts in.
        if AppSettings.shared.ignoreConcealed && isSensitive() {
            return .none
        }

        // 1. Files copied from Finder (stored as path references — tiny).
        //    Files use the existing sequential-paste flow, not the snapshot
        //    path, so they short-circuit here.
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map { $0.path }
            let thumb = paths.first.flatMap { Self.fileThumbnail(forPath: $0) }
            return .item(ClipItem(kind: .files, thumbnailData: thumb, filePaths: paths))
        }

        // 2. For everything else: snapshot every type the pasteboard exposes,
        //    drop anything that individually exceeds the per-rep cap, then
        //    derive a preview (.image / .richText / .text) from whichever
        //    high-fidelity rep survived. Apps that own private pasteboard
        //    types (Illustrator, Keynote, Office, Sketch, Affinity, etc.)
        //    get an editable paste-back because the snapshot is written to
        //    the pasteboard verbatim on paste.
        let snapshot = Self.collectSnapshot(from: pasteboard, perRepCap: cap)

        if let item = Self.itemFromSnapshot(snapshot) {
            return .item(item)
        }

        // No usable preview emerged from the snapshot. Either nothing was
        // capturable (snapshot is empty), or every preview-worthy rep was
        // dropped by the cap. Fire the not-saved warning when there really
        // *was* oversize content, so the user knows their copy didn't
        // persist instead of failing silently.
        if let oversized = Self.largestSkippedRep(from: pasteboard, perRepCap: cap) {
            return .oversize(bytes: oversized.bytes, kindLabel: oversized.label)
        }
        return .none
    }

    /// Pasteboard types that are markers / promises / sensitive flags rather
    /// than real content — never useful to round-trip back via paste.
    private static let skipSnapshotTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.apple.NSFilePromiseContent",
        "com.apple.pasteboard.promised-file-content-type",
        "com.apple.pasteboard.promised-file-url",
        "NSFilesPromisePboardType",
        "NSPromiseContentsPboardType"
    ]

    /// Per-type cap. Vector and app-native types get 4× the user's per-rep
    /// budget so a complex Illustrator artboard, Keynote slide, Word
    /// document fragment, etc. doesn't lose its editable round-trip just
    /// because its rep is chunkier than a screenshot. Raster reps (TIFF /
    /// PNG / JPEG) stay at the base setting because they're storage hogs
    /// and we can re-render them from PDF at paste time anyway.
    private static func capForType(_ raw: String, base: Int) -> Int {
        // Vector source-of-truth types.
        if raw == "com.adobe.pdf" || raw == "public.svg-image" {
            return base * 4
        }
        // App-native types — the only way to get an editable paste-back
        // into the originating app. Prefix-matched so we don't have to
        // enumerate every TSP* / AIP* / Word OOXML / Sketch / Affinity
        // variant by hand.
        for prefix in highValuePrefixes where raw.hasPrefix(prefix) {
            return base * 4
        }
        return base
    }

    /// UTI prefixes that identify "the editable native rep" for a major
    /// app. Match → gets the same 4× cap as PDF so a chunky native
    /// archive (Keynote's TSPNativeObject for a slide with embedded
    /// images can be 60-100 MB) doesn't lose its editable paste-back.
    private static let highValuePrefixes: [String] = [
        "com.apple.iWork.",            // Keynote / Pages / Numbers (TSPNativeObject, etc.)
        "com.apple.iWork-pb.",         // iWork pasteboard archive variants
        "com.adobe.illustrator.",      // AICB and friends
        "com.adobe.indesign.",         // InDesign spread/items
        "com.adobe.photoshop",         // .psd-on-pasteboard
        "com.microsoft.",              // Word / Excel / PowerPoint OOXML + OfficeDrawingObject
        "com.bohemiancoding.sketch.",  // Sketch
        "com.serif.affinity."          // Affinity Designer / Photo / Publisher
    ]

    /// Read every type from the pasteboard, filter markers/promises, and
    /// drop any single rep larger than the per-type cap. Returned dict
    /// carries the surviving types → data verbatim.
    private static func collectSnapshot(from pb: NSPasteboard,
                                        perRepCap base: Int) -> [String: Data] {
        guard let types = pb.types else { return [:] }
        var snap: [String: Data] = [:]
        for t in types {
            let raw = t.rawValue
            if skipSnapshotTypes.contains(raw) { continue }
            guard let data = pb.data(forType: t), data.count > 0 else { continue }
            if data.count > capForType(raw, base: base) { continue }
            snap[raw] = data
        }
        return snap
    }

    /// If the snapshot is empty, find out whether there *was* real content
    /// that we dropped for exceeding the cap, so the user gets the right
    /// warning (instead of silently doing nothing for an oversize copy).
    /// Uses the same per-type cap as `collectSnapshot` so a 150 MB PDF
    /// doesn't get reported as "oversize" when it would actually fit.
    private static func largestSkippedRep(from pb: NSPasteboard,
                                          perRepCap base: Int) -> (bytes: Int, label: String)? {
        guard let types = pb.types else { return nil }
        var biggest: (bytes: Int, label: String)?
        for t in types {
            let raw = t.rawValue
            if skipSnapshotTypes.contains(raw) { continue }
            guard let data = pb.data(forType: t) else { continue }
            if data.count <= capForType(raw, base: base) { continue }
            let label = friendlyKindLabel(forType: raw)
            if biggest == nil || data.count > biggest!.bytes {
                biggest = (data.count, label)
            }
        }
        return biggest
    }

    private static func friendlyKindLabel(forType raw: String) -> String {
        if raw.contains("pdf") { return "PDF" }
        if raw.contains("png") || raw.contains("tiff") || raw.contains("jpeg") || raw.contains("image") {
            return "image"
        }
        if raw.contains("rtf") || raw.contains("rich") { return "rich text" }
        if raw.contains("text") || raw.contains("plain") { return "text" }
        return "copy"
    }

    /// Pick the preview kind from the snapshot using the same priority order
    /// we used before snapshots existed: image (PDF/PNG/TIFF) → rich text →
    /// plain text. Returns nil if no preview-worthy type survived the cap —
    /// caller falls through to the oversize-warning check so the user
    /// learns *why* nothing got captured instead of failing silently.
    ///
    /// The full snapshot rides along on the resulting item regardless of
    /// which preview won, so paste-back is identical to the original even
    /// for apps whose primary representation is a private type.
    static func itemFromSnapshot(_ snap: [String: Data]) -> ClipItem? {
        // Image-like: PDF wins because design apps put it there alongside
        // PNG previews; capturing PDF preserves vector fidelity on paste.
        if let (data, utType) = pickImage(from: snap) {
            let image = NSImage(data: data)
            let thumb = image.flatMap { ImageUtils.thumbnailPNG(from: $0, maxDimension: 96) }
            let size = image.flatMap(ImageUtils.pixelSize)
            return ClipItem(
                kind: .image,
                imageData: data,
                imageUTType: utType,
                thumbnailData: thumb,
                pixelWidth: size?.width,
                pixelHeight: size?.height,
                pasteboardSnapshot: snap)
        }

        // Rich text.
        if let rtf = snap["public.rtf"] {
            let plain = (snap["public.utf8-plain-text"].flatMap { String(data: $0, encoding: .utf8) })
                ?? NSAttributedString(rtf: rtf, documentAttributes: nil)?.string
                ?? ""
            guard !plain.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
            return ClipItem(kind: .richText, text: plain, rtfData: rtf,
                            pasteboardSnapshot: snap)
        }

        // Plain text — try UTF-8 first, then NSString (latin-1) fallback.
        if let data = snap["public.utf8-plain-text"] ?? snap["public.text"] {
            let str = String(data: data, encoding: .utf8)
                ?? String(data: data, encoding: .isoLatin1)
                ?? ""
            guard !str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
            return ClipItem(kind: .text, text: str, pasteboardSnapshot: snap)
        }

        // Snapshot had only obscure types (e.g. Illustrator's AICB with no
        // PDF/PNG). Skip rather than show a placeholder we can't preview.
        return nil
    }

    private static func pickImage(from snap: [String: Data]) -> (Data, String)? {
        if let d = snap["com.adobe.pdf"] { return (d, "com.adobe.pdf") }
        if let d = snap["public.png"] { return (d, "public.png") }
        if let d = snap["public.tiff"] { return (d, "public.tiff") }
        if let d = snap["public.jpeg"] { return (d, "public.jpeg") }
        return nil
    }

    /// For a file-kind clip, generate an inline preview when the first path
    /// points at an image NSImage knows how to load (jpg/png/heic/gif/tiff/pdf).
    /// Returns nil for everything else so the row falls back to the generic
    /// file icon. Capped by file size so we don't read a 200 MB raw onto main.
    private static func fileThumbnail(forPath path: String) -> Data? {
        let maxFileBytes = 50 * 1024 * 1024
        if let size = try? FileManager.default
            .attributesOfItem(atPath: path)[.size] as? Int,
           size > maxFileBytes {
            return nil
        }
        guard let image = NSImage(contentsOfFile: path) else { return nil }
        return ImageUtils.thumbnailPNG(from: image, maxDimension: 96)
    }
}
