import AppKit

/// Polls the general pasteboard and feeds new copies into the store.
final class ClipboardMonitor {
    /// Fired when a copy was skipped because it exceeded the size cap.
    var onOversized: ((_ bytes: Int, _ kindLabel: String) -> Void)?

    private let store: ClipStore
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int
    /// When true, the next pasteboard change tick is treated as our own
    /// (e.g. the user picked an item from the menu and we re-wrote it to the
    /// pasteboard to synthesize ⌘V). We just bump lastChangeCount and skip
    /// adding it to history — so pasting a clip doesn't reorder it to the top.
    private var skipNextChange = false

    init(store: ClipStore) {
        self.store = store
        self.lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            self?.poll()
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Tell the monitor to ignore the very next pasteboard change — used when
    /// clipandcue itself writes to the pasteboard (e.g. delivering a picked
    /// clip) so the just-pasted item doesn't get re-added to the top.
    func suppressNextChange() {
        skipNextChange = true
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        if skipNextChange {
            skipNextChange = false
            return
        }

        switch readPasteboard() {
        case .none:
            break
        case .item(let item):
            store.add(item)
        case .oversize(let bytes, let label):
            onOversized?(bytes, label)
        }
    }

    private enum ReadResult {
        case none
        case item(ClipItem)
        case oversize(bytes: Int, kindLabel: String)
    }

    /// Types password managers / apps use to mark clipboard data as not-for-history.
    private static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private func isSensitive() -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains { Self.sensitiveTypes.contains($0.rawValue) }
    }

    private func readPasteboard() -> ReadResult {
        let cap = AppSettings.shared.sizeCapBytes

        // Respect password-manager flags when the user opts in.
        if AppSettings.shared.ignoreConcealed && isSensitive() {
            return .none
        }

        // 1. Files copied from Finder (stored as path references — tiny).
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map { $0.path }
            return .item(ClipItem(kind: .files, filePaths: paths))
        }

        // 2. Image data (screenshots, copied image regions).
        if let (data, utType) = bestImageData() {
            if data.count > cap {
                return .oversize(bytes: data.count, kindLabel: "image")
            }
            let image = NSImage(data: data)
            let thumb = image.flatMap { ImageUtils.thumbnailPNG(from: $0, maxDimension: 96) }
            return .item(ClipItem(
                kind: .image,
                imageData: data,
                imageUTType: utType,
                thumbnailData: thumb,
                pixelWidth: image.flatMap { ImageUtils.pixelSize($0)?.width },
                pixelHeight: image.flatMap { ImageUtils.pixelSize($0)?.height }))
        }

        // 3. Rich text (keep the RTF for fidelity, plus a plain-text preview).
        if let rtf = pasteboard.data(forType: .rtf) {
            if rtf.count > cap {
                return .oversize(bytes: rtf.count, kindLabel: "rich text")
            }
            let plain = pasteboard.string(forType: .string)
                ?? NSAttributedString(rtf: rtf, documentAttributes: nil)?.string
                ?? ""
            guard !plain.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return .none }
            return .item(ClipItem(kind: .richText, text: plain, rtfData: rtf))
        }

        // 4. Plain text.
        if let str = pasteboard.string(forType: .string) {
            guard !str.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return .none }
            if str.utf8.count > cap {
                return .oversize(bytes: str.utf8.count, kindLabel: "text")
            }
            return .item(ClipItem(kind: .text, text: str))
        }

        return .none
    }

    /// Prefer PNG, fall back to TIFF.
    private func bestImageData() -> (Data, String)? {
        if let png = pasteboard.data(forType: .png) {
            return (png, "public.png")
        }
        if let tiff = pasteboard.data(forType: .tiff) {
            return (tiff, "public.tiff")
        }
        return nil
    }
}
